### ISSUE TITLE
Consider using Register-ArgumentCompleter

### ISSUE THREAD

**Issue by lzybkr** [bergmeister/posh-dotnet#2]
Replacing `TabExpansion2` is not friendly to those who have customized it themselves, e.g. users of [TabExpansionPlusPlus](https://github.com/lzybkr/TabExpansionPlusPlus).

You could instead call `Register-ArgumentCompleter` - this cmdlet was introduced in V5 and should remove your need to replace `TabExpansion2`.

**Comment by bergmeister** [comment]
Thanks for all the great suggestions @lzybkr . This project was created very quickly because I could easily apply the same pattern for the new [vsts-cli](https://github.com/Microsoft/vsts-cli) for which I enabled tab completion in my [posh-vsts-cli](https://github.com/bergmeister/posh-vsts-cli) repo. However, I found out only an hour ago, that the .Net Core 2.0 CLI already has some tab completion capabilities but they are disabled by default, see [here](https://github.com/dotnet/cli/blob/master/Documentation/general/tab-completion.md) for how to enable it. Therefore most of your suggestions will probably be rather implemented in posh-vsts-cli where no tab completion exists at all and I should maybe add a comment in the readme

**Comment by lzybkr** [comment]
Oh, even better. That's a great pattern - but it would be nicer if they also generated tooltips.

I've considered contributing to [Rust's command line parser](https://github.com/kbknapp/clap-rs) so they generate tooltips when generating the PowerShell completer.
